### ISSUE TITLE
Creating divisions

### ISSUE THREAD

**Issue by mradvany** [mikewongtkd/freescoretkd#1]
Hi,

I accidentally posted this to the work program - sorry :/

I am trying to install the software on a Debian system to test it. Hoping to demo it at a tournament next Saturday October 3, 2015.

I cannot edit/create divisions. I suspect it is because there was an issue creating the database. I am able to get to the initial page that has options to register a ring device and manage divisions. The register ring device seems to be working. When I try to go to Manage World Class Poomsae Divisions I get a blank screen.

During installation, when I tried to change permission with "chmod -R a+w divisions" I got an error - 'divisions': no such file or directory. So I have created a dangling link. In which directory should the divisions file be located? Using find I could not find the file in the directory structure.

I would appreciate any assistance/guidance you could give me.

Marty

Martin Radvany
Vice president, Maryland State Tae Kwon Do Association

**Comment by potrero-scientific-llc** [comment]
Hi Marty,

Sorry to have missed the party; this is a volunteer project, and work has been relentless, so I haven't had time to do much support.

To the point, the division editing system is still being designed, mostly because the scope changes when dealing with different registration systems.

Fundamentally the database is comprised of human-readable division text files in a ring directory. Rings are named: "ring01", "ring02", and so forth, and a special ring "staging" where unassigned divisions can be placed until the athletes are ready to be sent to a ring. You can look in the trunk/backend/test/data directory for examples of the division files. I recommend copying these examples, renaming them as you need (following the pattern: div.p01.txt, div p02.txt, etc.) and editing the contents. Basically it's some header information (e.g. division description, number of judges, etc.), followed by a list of athlete names.

Be careful when copying and editing text files; reload the display screen after every edit to ensure that the data parses properly. There's still work to be done to have meaningful error messages for data parsing errors.

Best regards,

- mike

**Comment by mikewongtkd** [comment]
Hi Marty,

Sorry to have missed the party; this is a volunteer project, and work has been relentless, so I haven't had time to do much support.

To the point, the division editing system is still being designed, mostly because the scope changes when dealing with different registration systems.

Fundamentally the database is comprised of human-readable division text files in a ring directory. Rings are named: "ring01", "ring02", and so forth, and a special ring "staging" where unassigned divisions can be placed until the athletes are ready to be sent to a ring. You can look in the trunk/backend/test/data directory for examples of the division files. I recommend copying these examples, renaming them as you need (following the pattern: div.p01.txt, div p02.txt, etc.) and editing the contents. Basically it's some header information (e.g. division description, number of judges, etc.), followed by a list of athlete names.

Be careful when copying and editing text files; reload the display screen after every edit to ensure that the data parses properly. There's still work to be done to have meaningful error messages for data parsing errors.

Best regards,

- mike
